### ISSUE TITLE
change login url

### ISSUE THREAD

**Issue by domdinicola** [unicef/drips-fe#3] opened 2022-06-07 16:53 UTC
change current login url with `drips/social/login/unicef-azuread-tenant-oauth2/`

**Comment by danNordlogic** [comment] 2022-06-07 19:53
Fixed with https://github.com/unicef/drips-fe/pull/5

**Comment by ntrncic** [comment] 2022-06-09 10:04
> Fixed with #5

@danNordlogic still the issue is there. how about changing this  <Link href="/sociallogin/unicef-azuread-b2c-oauth2/">Sign In</Link> on the page?

**Closed** 2022-06-10 15:43 UTC
